api_version = "2026-07"

[[extensions]]
name = "t:name"
handle = "parks-cart-checkout-validation"
type = "function"
uid = "bbe0d75a-30bc-0e62-4adb-a4474fe2978227ad50cb"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.validations.generate.run"
  input_query = "src/cart_validations_generate_run.graphql"
  export = "cart-validations-generate-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"
