# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ffffa296da9406ca2857d6ecf0f249df"
name = "parks-gwp-cart-transformer"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_products,write_cart_transforms,write_products,write_validations"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]
