query CartValidationsGenerateRunInput {
  buyerJourney {
    step
  }
  localization {
    country {
      isoCode
    }
  }
  cart {
    buyerIdentity {
      isAuthenticated
    }
    cost {
      subtotalAmount {
        amount
        currencyCode
      }
    }
    lines {
      quantity
      cost {
        amountPerQuantity {
          amount
        }
      }
      merchandise {
        __typename
        ... on ProductVariant {
          id
        }
      }
      giftMarker: attribute(key: "_gwp_gift") {
        value
      }
    }
  }
  shop {
    metafield(namespace: "$app:gwp", key: "config") {
      jsonValue
    }
  }
}
