api_version = "2026-07"

[[extensions]]
name = "t:name"
handle = "parks-cart-transformer"
type = "function"
uid = "4e34133e-0f52-0f23-8fdc-dfaad827c31ed6a60907"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.transform.run"
  input_query = "src/cart_transform_run.graphql"
  export = "cart-transform-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
